version: 0.2

phases:
  build:
    commands:
      - df -h 
      - ls -lah  /var/codebuild/reserve/
      - echo "Filling disk space until 10MB remains..."
      - rm -rf your_file.bin
      - df -h 
      - ls -lah  /var/codebuild/reserve
