version: 0.2

phases:
  build:
    commands:
      - df -h 
      - ls -lah  /var/codebuild/reserve/
      - echo "Filling disk space until 10MB remains..."
      - sudo python3 disk_fill.py
      - ls -lah  /var/codebuild/reserve
      - hostname
